/* Beacon 2.5 settings backup/restore. No network use. */
'use strict';
(()=>{
 const $=id=>document.getElementById(id);
 const status=(s,bad=false)=>{const e=$('backupStatus'); e.textContent=s;e.className=bad?'error':'muted'};
 const secret=(k)=>k==='beacon:web:account'||k==='beacon:hub:torbox'||k==='beacon:hub:premiumize';
 const allowed=(k)=>k.startsWith('beacon:') && /^[a-zA-Z0-9:_./-]{1,256}$/.test(k) && !k.startsWith('beacon:backup:');
 const enc=new TextEncoder(),dec=new TextDecoder();
 const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b)));
 const un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
 const stores=()=>({local:localStorage,session:sessionStorage});
 function gather(includeSecrets){const data={local:{},session:{}};for(const [scope,store] of Object.entries(stores())){for(let i=0;i<store.length;i++){const key=store.key(i);if(!allowed(key))continue;if(secret(key)&&!includeSecrets)continue;data[scope][key]=store.getItem(key)}}return data}
 async function keyFor(password,salt){const raw=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
 async function encrypt(data,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const key=await keyFor(password,salt);const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(data)));return {format:'beacon-backup',version:1,encrypted:true,kdf:'PBKDF2-SHA256',iterations:250000,salt:b64(salt),iv:b64(iv),data:b64(ciphertext)}}
 async function decrypt(blob,password){if(blob.kdf!=='PBKDF2-SHA256'||blob.iterations!==250000)throw Error('Unsupported encryption settings');const key=await keyFor(password,un64(blob.salt));return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(blob.iv)},key,un64(blob.data))))}
 function validSection(o){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).length>300)throw Error('Invalid backup section');for(const [key,v] of Object.entries(o)){if(!allowed(key)||typeof v!=='string'||v.length>3000000)throw Error('Invalid setting in backup')}}
 function apply(data,encrypted){if(!data||typeof data!=='object')throw Error('Invalid backup');validSection(data.local);validSection(data.session);if(!encrypted&&[...Object.keys(data.local),...Object.keys(data.session)].some(secret))throw Error('Unencrypted backup cannot contain credentials');let count=0;for(const [scope,entries] of Object.entries({local:data.local,session:data.session})){for(const [k,v] of Object.entries(entries)){if(secret(k)&&!encrypted)throw Error('Unencrypted backup cannot contain credentials');const target=(k==='beacon:hub:torbox'||k==='beacon:hub:premiumize')?'local':scope;stores()[target].setItem(k,v);if(target==='local'&&scope==='session')sessionStorage.removeItem(k);count++}}return count}
 function download(obj){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Beacon-settings-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 $('exportBackup').onclick=async()=>{try{const include=$('backupSecrets').checked,password=$('backupPassword').value;if(include&&password.length<12)throw Error('Use a passphrase of at least 12 characters');const data=gather(include);const payload=include?await encrypt(data,password):{format:'beacon-backup',version:1,encrypted:false,data};download(payload);status('Backup downloaded. '+(include?'Encrypted credentials included.':'Account credentials excluded.'))}catch(e){status('Backup failed: '+e.message,true)}};
 $('importBackup').onclick=async()=>{try{const file=$('importBackupFile').files?.[0];if(!file)throw Error('Choose a backup JSON file first');if(file.size>6000000)throw Error('Backup too large');const payload=JSON.parse(await file.text());if(payload.format!=='beacon-backup'||payload.version!==1)throw Error('Unrecognized backup');let data;if(payload.encrypted){if(!$('backupPassword').value)throw Error('Enter backup passphrase');data=await decrypt(payload,$('backupPassword').value)}else data=payload.data;if(!confirm('Import settings into this Beacon installation? Existing matching settings will be replaced.'))return;const count=apply(data,Boolean(payload.encrypted));status('Imported '+count+' settings. Reloading to apply…');setTimeout(()=>location.reload(),900)}catch(e){status('Import failed: '+e.message,true)}};
})();
