'use strict';
const $=s=>document.querySelector(s);
const KEY='beacon:hub:vendors:v1';
const stash=(k,v)=>{localStorage.setItem('beacon:hub:'+k,v);sessionStorage.removeItem('beacon:hub:'+k)};
const credential=k=>localStorage.getItem('beacon:hub:'+k)||sessionStorage.getItem('beacon:hub:'+k)||'';
for(const k of ['torbox','premiumize']){const key='beacon:hub:'+k,old=sessionStorage.getItem(key);if(old&&!localStorage.getItem(key))localStorage.setItem(key,old);if(old)sessionStorage.removeItem(key)}
let vendors=[];try{vendors=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{};
let library=[];
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notify=(msg,error=false)=>{const el=$('#notice');el.textContent=msg;el.className=error?'error':''};
const save=()=>localStorage.setItem(KEY,JSON.stringify(vendors));
const http=async(url,options={})=>{const r=await fetch(url,{...options,signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()};
const tb=async(path,params={})=>{const url=new URL('https://api.torbox.app/v1/api/'+path);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const data=await http(url,{headers:{Authorization:'Bearer '+credential('torbox')}});if(data.success===false)throw Error(data.detail||data.error||'TorBox error');return data.data};
const pm=async(path,params={})=>{const url=new URL('https://www.premiumize.me/api/'+path);url.searchParams.set('apikey',credential('premiumize'));Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const data=await http(url);if(data.status!=='success')throw Error(data.message||'Premiumize error');return data};
function tabs(name){document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('hidden',el.id!==name));document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===name));$('#heading').textContent={library:'Cloud Library',providers:'Vendors & Packages',accounts:'Connected Accounts',history:'Watch History'}[name]}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tabs(b.dataset.tab)));
function normalizedVendor(obj,origin){if(!obj||obj.beaconVendor!==1||!Array.isArray(obj.packages)||typeof obj.name!=='string')throw Error('Not a Beacon vendor manifest. Syncler packages require a separate compatibility engine.');const packages=obj.packages.map((p,i)=>{if(!p||!Array.isArray(p.items))throw Error('Package requires an items array');return {id:String(p.id||i),name:String(p.name||'Package'),enabled:true,items:p.items.map(x=>{if(!x.title||!x.url||!/^https:\/\//i.test(x.url))throw Error('Each item needs a title and HTTPS media URL');return {title:String(x.title),type:String(x.type||'movie'),url:String(x.url)}})}});return {id:crypto.randomUUID(),name:obj.name,origin,packages}}
async function installVendor(url,fileObj){try{const v=normalizedVendor(fileObj||await http(url),url||'Local file');vendors.push(v);save();renderVendors();notify(`Added ${v.name} (${v.packages.length} package(s))`)}catch(e){notify(e.message,true)}}
$('#addVendor').onclick=()=>{const url=$('#vendorUrl').value.trim();if(!/^https:\/\//i.test(url))return notify('Enter an HTTPS URL',true);installVendor(url)};
$('#vendorFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{installVendor('',JSON.parse(await file.text()))}catch(err){notify(err.message,true)}e.target.value=''};
function renderVendors(){const root=$('#vendorsList');root.replaceChildren();if(!vendors.length)root.textContent='No vendors installed. Add a Beacon-compatible vendor manifest above.';for(const v of vendors){const node=document.createElement('div');node.className='vendorrow';const info=document.createElement('div');const name=document.createElement('strong');name.textContent=v.name;info.append(name);const sub=document.createElement('p');sub.className='muted';sub.textContent=`${v.origin} • ${v.packages.length} package(s)`;info.append(sub);const actions=document.createElement('div');actions.className='vendorbuttons';v.packages.forEach((p)=>{const b=document.createElement('button');b.textContent=(p.enabled?'✓ ':'○ ')+p.name;b.onclick=()=>{p.enabled=!p.enabled;save();renderVendors()};actions.append(b)});const remove=document.createElement('button');remove.textContent='Remove';remove.onclick=()=>{vendors=vendors.filter(x=>x.id!==v.id);save();renderVendors()};actions.append(remove);node.append(info,actions);root.append(node)}}
function setStatuses(){for(const [id,key] of [['torboxStatus','torbox'],['premiumizeStatus','premiumize']])$('#'+id).textContent=credential(key)?'Connected (saved in this Chrome profile)':'Not connected';$('#sources').textContent=['torbox','premiumize'].filter(credential).length;$('#packagesCount').textContent=vendors.flatMap(v=>v.packages).filter(p=>p.enabled).length}
async function connectService(k,field,fn){const value=$(field).value.trim();if(!value)return notify('Enter an API key first',true);stash(k,value);try{await fn();notify(`${k==='torbox'?'TorBox':'Premiumize'} connection verified`);$(field).value='';setStatuses();await reload()}catch(e){localStorage.removeItem('beacon:hub:'+k);sessionStorage.removeItem('beacon:hub:'+k);setStatuses();notify(`Connection failed: ${e.message}`,true)}}
$('#saveTorbox').onclick=()=>connectService('torbox','#torboxKey',()=>tb('user/me'));
$('#savePremiumize').onclick=()=>connectService('premiumize','#premiumizeKey',()=>pm('account/info'));
for(const [id,k] of [['removeTorbox','torbox'],['removePremiumize','premiumize']])$('#'+id).onclick=()=>{localStorage.removeItem('beacon:hub:'+k);sessionStorage.removeItem('beacon:hub:'+k);setStatuses();notify('Account disconnected')};
$('#clearData').onclick=()=>{if(confirm('Clear Beacon media hub vendors and saved credentials?')){vendors=[];save();for(const k of ['torbox','premiumize']){localStorage.removeItem('beacon:hub:'+k);sessionStorage.removeItem('beacon:hub:'+k)}renderVendors();setStatuses();reload()}};
async function reload(){notify('Loading connected libraries…');const results=[];const problems=[];for(const v of vendors)for(const p of v.packages)if(p.enabled)for(const item of p.items)results.push({...item,source:v.name,kind:'url'});
if(credential('premiumize'))try{async function loadFolder(id,depth){const data=await pm('folder/list',id?{id}:{});for(const x of data.content||[]){if(x.type==='folder'&&depth<2)await loadFolder(x.id,depth+1);else if(x.type==='file'&&x.link)results.push({title:x.name||'File',source:'Premiumize',kind:'url',url:x.link})}}await loadFolder('',0)}catch(e){problems.push('Premiumize: '+e.message)};
if(credential('torbox'))try{const list=await tb('torrents/mylist',{limit:100});for(const torrent of Array.isArray(list)?list:[]){if(!['cached','completed','uploading'].includes(torrent.download_state))continue;for(const file of torrent.files||[]){if(!/\.(mp4|mkv|webm|m4v|mov)$/i.test(file.name||file.short_name||''))continue;results.push({title:file.name||file.short_name||torrent.name||'Video',source:'TorBox',kind:'torbox',torrentId:torrent.id,fileId:file.id})}}}catch(e){problems.push('TorBox: '+e.message)};
library=results;renderLibrary();setStatuses();notify(problems.length?problems.join(' | '):`${results.length} item(s) available`,!!problems.length)}
const BEACON_HIDDEN_CLOUD='beacon:media:hidden-cloud:v1';
let hiddenCloud=new Set();try{hiddenCloud=new Set(JSON.parse(localStorage.getItem(BEACON_HIDDEN_CLOUD)||'[]'))}catch{}
function cloudKey(item){return [item.source,item.kind,item.torrentId||'',item.fileId||'',item.title].join('::')}
function renderLibrary(){const query=$('#search').value.toLowerCase().trim();const found=library.filter(x=>!hiddenCloud.has(cloudKey(x))&&x.title.toLowerCase().includes(query));$('#count').textContent=library.filter(x=>!hiddenCloud.has(cloudKey(x))).length;const root=$('#results');root.replaceChildren();if(!found.length){const empty=document.createElement('p');empty.className='muted';empty.textContent='No visible cloud items. Hidden items are not deleted from either cloud account.';root.append(empty);return}for(const item of found){const t=document.createElement('div');t.className='tile';const art=window.BeaconExperience?.posterFor(item.title);if(art){const img=document.createElement('img');img.src=art;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.className='beacon-poster';t.append(img)}const tag=document.createElement('span');tag.className='tag';tag.textContent=item.source;const heading=document.createElement('strong');heading.textContent=item.title;const caption=document.createElement('p');caption.textContent=item.kind==='torbox'?'TorBox cloud file':'Playable media link';const b=document.createElement('button');b.textContent='Play ▶';b.onclick=()=>play(item);const hide=document.createElement('button');hide.textContent='Hide from Beacon';hide.onclick=()=>{hiddenCloud.add(cloudKey(item));localStorage.setItem(BEACON_HIDDEN_CLOUD,JSON.stringify([...hiddenCloud]));renderLibrary()};t.append(tag,heading,caption,b,hide);root.append(t)}}
function restoreHiddenCloud(){hiddenCloud.clear();localStorage.removeItem(BEACON_HIDDEN_CLOUD);renderLibrary()}
async function play(item){try{notify('Preparing media…');let url=item.url;if(item.kind==='torbox'){if(!credential('torbox'))throw Error('Reconnect TorBox first');url=await tb('torrents/requestdl',{token:credential('torbox'),torrent_id:item.torrentId,file_id:item.fileId})}if(!/^https?:\/\//i.test(url||''))throw Error('No playable URL returned');$('#playingTitle').textContent=item.title;$('#player').classList.remove('hidden');window.BeaconExperience?.begin(item,$('#video'),url);$('#video').src=url;$('#video').play().catch(()=>{});notify('Playback launched')}catch(e){notify('Unable to start playback: '+e.message,true)}}
function closePlayer(){window.BeaconExperience?.flush();$('#video').pause();$('#video').removeAttribute('src');$('#video').load();$('#player').classList.add('hidden')};$('#closePlayer').onclick=closePlayer;$('#reload').onclick=reload;$('#search').oninput=renderLibrary;renderVendors();setStatuses();reload();

// Local UI hide is independent of clearing playback history.
$('#restoreCloudCards')?.addEventListener('click',restoreHiddenCloud);

// Beacon 4.0: open a specific tab from links in the new interface (media.html#providers / #accounts / #history).
{const t=location.hash.slice(1);if(['library','providers','history','accounts'].includes(t))tabs(t);}
