#!/usr/bin/env node
/* Beacon documentation tooling. No dependencies (like the server).
 *
 *   node scripts/docs.mjs new <kind> "Title"   start a history record (journal|decision|incident|experiment|correction)
 *   node scripts/docs.mjs index                rewrite docs/history/_index.md from the records
 *   node scripts/docs.mjs check [--base <ref>] links, record format, index freshness, append-only history
 *
 * Append-only: a record that exists at the merge base with <ref> (default origin/backend) must be byte-identical in
 * the working tree, except for its front-matter `status:` line. Corrections and reversals are new records
 * (see docs/history/README.md).
 */
'use strict';

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const HISTORY = join(ROOT, 'docs/history');
const INDEX = join(HISTORY, '_index.md');

export const KINDS = {
  journal:    { prefix: 'JRN', dir: 'journal',     heading: 'Journal',     status: ['in-progress', 'done', 'abandoned'] },
  decision:   { prefix: 'ADR', dir: 'decisions',   heading: 'Decisions',   status: ['proposed', 'accepted', 'rejected'] },
  incident:   { prefix: 'INC', dir: 'incidents',   heading: 'Incidents',   status: ['open', 'resolved', 'mitigated'] },
  experiment: { prefix: 'EXP', dir: 'experiments', heading: 'Experiments', status: ['planned', 'done', 'inconclusive'] },
  correction: { prefix: 'COR', dir: 'corrections', heading: 'Corrections', status: ['done'] },
};
const REQUIRED = ['id', 'type', 'title', 'date', 'recorded', 'source', 'status'];
const SOURCES = ['contemporaneous', 'reconstructed'];
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const SKIP_LINKS = /^docs\/beacon-hub\//;           // Barr's documents, kept as he wrote them

const git = (...args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
const today = () => new Date().toLocaleDateString('en-CA');   // YYYY-MM-DD, local time

/* Front matter: `key: value` lines, values may be [a, b] lists. Enough for our records; not general YAML. */
export function parseFrontMatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) return null;
  const data = {};
  for (const line of m[1].split('\n')) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const kv = line.match(/^([a-z_]+):\s*(.*?)\s*$/);
    if (!kv) return { __error: `bad front matter line: ${line}` };
    let v = kv[2];
    if (v.startsWith('[') && v.endsWith(']')) v = v.slice(1, -1).split(',').map(s => s.trim()).filter(Boolean);
    else if (/^".*"$/.test(v)) v = v.slice(1, -1);
    data[kv[1]] = v;
  }
  return data;
}

function records() {
  const out = [];
  for (const [type, k] of Object.entries(KINDS)) {
    const dir = join(HISTORY, k.dir);
    if (!existsSync(dir)) continue;
    for (const name of readdirSync(dir).filter(n => n.endsWith('.md')).sort()) {
      const file = join(dir, name);
      out.push({ type, kind: k, name, file, rel: relative(ROOT, file), meta: parseFrontMatter(readFileSync(file, 'utf8')) });
    }
  }
  return out;
}

function renderIndex(recs) {
  const supersededBy = {};
  for (const r of recs) for (const id of [].concat(r.meta?.supersedes || [])) (supersededBy[id] ||= []).push(r.meta.id);
  const lines = [
    '# History index', '',
    '*Generated by `node scripts/docs.mjs index`. Do not edit by hand. The records themselves are append-only; see [README.md](README.md).*', '',
  ];
  for (const [type, k] of Object.entries(KINDS)) {
    const mine = recs.filter(r => r.type === type && r.meta && !r.meta.__error);
    lines.push(`## ${k.heading}`, '');
    if (!mine.length) { lines.push('None yet.', ''); continue; }
    lines.push('| ID | Date | Title | Status | Source |', '|---|---|---|---|---|');
    for (const r of mine) {
      const sup = supersededBy[r.meta.id] ? ` (superseded by ${supersededBy[r.meta.id].join(', ')})` : '';
      lines.push(`| [${r.meta.id}](${k.dir}/${r.name}) | ${r.meta.date} | ${r.meta.title} | ${r.meta.status}${sup} | ${r.meta.source} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function cmdNew(kindArg, title) {
  const type = Object.keys(KINDS).find(t => t === kindArg || KINDS[t].prefix.toLowerCase() === String(kindArg).toLowerCase() || (t === 'decision' && kindArg === 'adr'));
  if (!type || !title) die(`usage: docs.mjs new <${Object.keys(KINDS).join('|')}> "Title"`);
  const k = KINDS[type];
  const used = records().filter(r => r.type === type).map(r => Number(r.meta?.id?.split('-')[1]) || 0);
  const id = `${k.prefix}-${String(Math.max(0, ...used) + 1).padStart(4, '0')}`;
  const slug = title.toLowerCase().normalize('NFKD').replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
  const file = join(HISTORY, k.dir, `${id}-${slug}.md`);
  const tpl = readFileSync(join(HISTORY, 'templates', `${type}.md`), 'utf8');
  writeFileSync(file, tpl.replaceAll('{{id}}', id).replaceAll('{{title}}', title).replaceAll('{{date}}', today()), { flag: 'wx' });
  console.log(relative(ROOT, file));
}

function cmdIndex() {
  writeFileSync(INDEX, renderIndex(records()));
  console.log(relative(ROOT, INDEX));
}

function markdownFiles() {
  const listed = git('ls-files', '-co', '--exclude-standard', '--', '*.md').split('\n').filter(Boolean);
  return listed.filter(f => existsSync(join(ROOT, f)) && !SKIP_LINKS.test(f));
}

function checkLinks(problems) {
  for (const rel of markdownFiles()) {
    const text = readFileSync(join(ROOT, rel), 'utf8').replace(/```[\s\S]*?```/g, '').replace(/`[^`\n]*`/g, '');
    for (const [, target] of text.matchAll(/\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)) {
      if (/^(https?:|mailto:|#)/.test(target)) continue;
      const path = decodeURIComponent(target.split('#')[0]);
      if (!existsSync(resolve(dirname(join(ROOT, rel)), path))) problems.push(`${rel}: broken link → ${target}`);
    }
  }
}

function checkRecords(recs, problems) {
  const ids = new Map();
  for (const r of recs) {
    const m = r.meta;
    if (!m) { problems.push(`${r.rel}: no front matter`); continue; }
    if (m.__error) { problems.push(`${r.rel}: ${m.__error}`); continue; }
    for (const key of REQUIRED) if (!m[key]) problems.push(`${r.rel}: missing "${key}"`);
    if (m.type && m.type !== r.type) problems.push(`${r.rel}: type "${m.type}" but it's in ${r.kind.dir}/`);
    if (m.id && !new RegExp(`^${r.kind.prefix}-\\d{4}$`).test(m.id)) problems.push(`${r.rel}: id "${m.id}" should look like ${r.kind.prefix}-0001`);
    if (m.id && !r.name.startsWith(m.id + '-')) problems.push(`${r.rel}: file name should start with "${m.id}-"`);
    if (m.source && !SOURCES.includes(m.source)) problems.push(`${r.rel}: source must be ${SOURCES.join(' or ')}`);
    if (m.status && !r.kind.status.includes(m.status)) problems.push(`${r.rel}: status must be one of ${r.kind.status.join(', ')}`);
    for (const key of ['date', 'recorded']) if (m[key] && !DATE.test(m[key])) problems.push(`${r.rel}: ${key} must be YYYY-MM-DD`);
    if (m.id) { if (ids.has(m.id)) problems.push(`${r.rel}: id ${m.id} also used by ${ids.get(m.id)}`); else ids.set(m.id, r.rel); }
  }
  for (const r of recs) for (const key of ['supersedes', 'corrects', 'related']) {
    for (const id of [].concat(r.meta?.[key] || [])) if (!ids.has(id)) problems.push(`${r.rel}: ${key} names unknown record ${id}`);
  }
  if (!existsSync(INDEX) || readFileSync(INDEX, 'utf8') !== renderIndex(recs)) problems.push('docs/history/_index.md is out of date: run node scripts/docs.mjs index');
}

const sansStatus = text => text.replace(/^(---\n[\s\S]*?)^status:.*\n/m, '$1');

function checkAppendOnly(base, problems, notes) {
  let mergeBase;
  try { mergeBase = git('merge-base', base, 'HEAD').trim(); }
  catch { notes.push(`append-only check skipped: can't find base "${base}" (fetch it, or pass --base <ref>)`); return; }
  const isRecord = p => /^docs\/history\/(journal|decisions|incidents|experiments|corrections)\/[^/]+\.md$/.test(p);
  // Working tree (staged or not) against the merge base: catches committed and uncommitted edits alike.
  for (const line of git('diff', '--name-status', '-M', mergeBase, '--', 'docs/history').split('\n').filter(Boolean)) {
    const [status, from, to] = line.split('\t');
    if (status === 'A' || !isRecord(from)) continue;
    // The one allowed edit: the front-matter status line (proposed → accepted, open → resolved, …).
    if (status === 'M' && sansStatus(git('show', `${mergeBase}:${from}`)) === sansStatus(readFileSync(join(ROOT, from), 'utf8'))) {
      notes.push(`${from}: status changed (allowed)`);
      continue;
    }
    const what = status === 'D' ? 'deleted' : status.startsWith('R') ? `renamed to ${to}` : 'modified';
    problems.push(`${from}: ${what}. History records are append-only; write a correction (COR) or a superseding record instead`);
  }
  const uncommitted = git('ls-files', '--others', '--exclude-standard', '--', 'docs/history').split('\n').filter(isRecord);
  if (uncommitted.length) notes.push(`${uncommitted.length} new record${uncommitted.length === 1 ? '' : 's'} not yet committed`);
  notes.push(`append-only checked against ${base} (merge base ${mergeBase.slice(0, 7)})`);
}

function cmdCheck(args) {
  const i = args.indexOf('--base');
  const base = i >= 0 ? args[i + 1] : 'origin/backend';
  const problems = [], notes = [];
  checkLinks(problems);
  checkRecords(records(), problems);
  checkAppendOnly(base, problems, notes);
  for (const n of notes) console.log(`note: ${n}`);
  if (problems.length) {
    for (const p of problems) console.error(`✗ ${p}`);
    console.error(`\n${problems.length} problem${problems.length === 1 ? '' : 's'}`);
    process.exit(1);
  }
  console.log(`✓ docs ok (${records().length} history records)`);
}

function die(msg) { console.error(msg); process.exit(2); }

const [cmd, ...rest] = process.argv.slice(2);
if (cmd === 'new') cmdNew(rest[0], rest.slice(1).join(' '));
else if (cmd === 'index') cmdIndex();
else if (cmd === 'check') cmdCheck(rest);
else die('usage: node scripts/docs.mjs new <kind> "Title" | index | check [--base <ref>]');
